
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agqsyfcfpjgesxetwxhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFncXN5ZmNmcGpnZXN4ZXR3eGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MjgwNzAsImV4cCI6MjA1NzAwNDA3MH0.CWgzLXtyKol1yZRZETJcU8_bK2G_yI5AX_I3GL1asKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
